[package]
name = "serde_fs"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0.30"
itoa = "0.4.8"
serde_json = "1.0.89"

[dev-dependencies]
pretty_assertions = "1.3.0"
rand = "0.8.5"
serde_bytes = "0.11"
